import React from "react";

const Box = ({ text, color = "bg-green-200", shape = "square" }) => {
    const baseClasses = "text-black text-sm px-4 py-4 shadow-md text-center";
    const shapeClass =
        shape === "diamond"
            ? "rotate-45 w-28 h-28 flex items-center justify-center text-black bg-orange-300"
            : shape === "circle"
                ? "rounded-full bg-white text-black border w-28 h-28 flex items-center justify-center"
                : "rounded bg-green-400";

    return (
        <div className={`flex items-center justify-center ${shape === "square" ? color : ""}`}>
            <div className={`${baseClasses} ${shapeClass}`}>
                <div className={`${shape === "diamond" ? "-rotate-45" : ""}`}>{text}</div>
            </div>
        </div>
    );
};

const Section_f = () => {
    return (
        <section className="min-h-screen px-4 py-16 bg-[#F5F2EC]">
            <div className="max-w-7xl mx-auto bg-white p-6 sm:p-10 rounded-xl shadow-md text-center">
                <h2 className="text-5xl font-black mb-12 text-center">
                    <span className="text-[#2A2523]">USER </span>
                    <span className="text-[#B59F83]">FLOW</span>
                </h2>

                <div className="flex items-center justify-center gap-6 flex-wrap">
                    <Box text="Explore" shape="circle" />
                    <Box text="Search Bar" />
                    <Box text="User enters desired search terms" />
                    <Box text="Results" />
                    <Box text="Choose a listing to view" shape="diamond" />
                    <Box text="Host description of property" />
                    <Box text="Pricing" />
                    <Box text="User books the place" />
                    <Box text="Map" />
                    <Box text="Nearby Activities" />
                    <Box text="Purchase the ticket to the activities" />
                </div>

                {/* Row 2 */}
                <div className="mt-16 flex items-center justify-center gap-6 flex-wrap">
                    <Box text="User reads autogenerated itinerary" />
                    <Box text="Decide to add, subtract..." shape="diamond" />
                    <Box text="View details" />
                    <Box text="Reads details of event" color="bg-yellow-300" />
                    <Box text="Taps trash icon to delete" color="bg-yellow-300" />
                    <Box text="Subtract" />
                    <Box text="Taps '+' button" />
                    <Box text="New page appears..." />
                    <Box text="Fills out itinerary form" />
                    <Box text="Taps Save Button" />
                    <Box text="Sees event added" />
                </div>
            </div>
        </section>
    );
};

export default Section_f;
